const state={code:'000922.CSI',metric:'pe_ttm_index',series:[],summary:null,viewport:{valuation:{start:0,end:0,grain:'auto',range:'20y'},spread:{start:0,end:0,grain:'auto',range:'20y'}}};
const indexNames=Object.freeze({'000824.CSI':'中证国有企业红利指数','000825.CSI':'中证中央企业红利指数','000826.CSI':'中证民营企业红利指数','000922.CSI':'中证红利指数','921468.CSI':'中证红利质量全收益指数','931231.CSI':'中证央企红利50指数'});
const indexLabel=code=>`${indexNames[code]||'未命名指数'} · ${code}`;
const labels={pe_ttm_index:'PE (TTM)',pb_mrq:'PB (MRQ)',ps:'PS',pcf:'PCF',dividend_yield:'股息率'};
const finite=v=>v!==null&&v!==undefined&&Number.isFinite(Number(v));
const number=(v,d=2)=>finite(v)?Number(v).toFixed(d):'—';
const compactDate=v=>v?v.slice(2).replaceAll('-','.'): '—';
async function getJson(path){const r=await fetch(path);if(!r.ok)throw new Error(await r.text());return r.json()}
function startForRange(range){if(range==='all'||!state.series.length)return 0;const years=Number(range.replace('y','')),latest=state.series.at(-1)?.trade_date;if(!Number.isFinite(years)||!latest)return 0;const cutoff=new Date(`${latest}T00:00:00`);cutoff.setFullYear(cutoff.getFullYear()-years);const start=state.series.findIndex(row=>row.trade_date>=cutoff.toISOString().slice(0,10));return start<0?0:start}
function syncRangeControl(key){const control=document.querySelector(`[data-range-chart="${key}"]`);if(control)control.value=state.viewport[key].range}
function applyRange(key,range){const view=state.viewport[key];view.range=range;view.start=startForRange(range);view.end=state.series.length;syncRangeControl(key)}
function resetViewports(){Object.keys(state.viewport).forEach(key=>applyRange(key,state.viewport[key].range))}
function rangeData(key){const v=state.viewport[key];return state.series.slice(v.start,v.end||state.series.length)}
function resolvedGrain(key,rows){const selected=state.viewport[key].grain;if(selected!=='auto')return selected;return rows.length>1500?'month':rows.length>420?'week':'day'}
function aggregate(rows,grain){if(grain==='day')return rows;const map=new Map();rows.forEach(row=>{const date=new Date(`${row.trade_date}T00:00:00`);const monday=new Date(date);monday.setDate(date.getDate()-((date.getDay()+6)%7));map.set(grain==='week'?monday.toISOString().slice(0,10):row.trade_date.slice(0,7),row)});return[...map.values()]}
function sigma(row,multiple){return finite(row.rolling_mean)&&finite(row.rolling_std)?Number(row.rolling_mean)+multiple*Number(row.rolling_std):Number.NaN}
function chartLines(key){if(key==='valuation')return[{accessor:r=>r[state.metric],className:'series-main',name:labels[state.metric]}];return[{accessor:r=>r.bond_minus_dividend,className:'series-main',name:'股债收益差'},{accessor:r=>r.rolling_mean,className:'series-blue',name:'滚动均值'},{accessor:r=>sigma(r,1),className:'sigma-one',name:'+1σ'},{accessor:r=>sigma(r,-1),className:'sigma-one',name:'-1σ'},{accessor:r=>sigma(r,2),className:'sigma-two',name:'+2σ'},{accessor:r=>sigma(r,-2),className:'sigma-two',name:'-2σ'}]}
function pathFor(data,fn,sx,sy){let active=false,out='';data.forEach((row,i)=>{const value=fn(row);if(!finite(value)){active=false;return}out+=`${active?'L':'M'}${sx(i).toFixed(2)},${sy(Number(value)).toFixed(2)} `;active=true});return out}
function tooltipHtml(key,row,grain){const title=grain==='day'?row.trade_date:`${row.trade_date}（${grain==='week'?'周末':'月末'}）`;if(key==='valuation')return`<b>${title}</b><span>${labels[state.metric]} <strong>${number(row[state.metric])}</strong></span><span>收盘价 <strong>${number(row.close,4)}</strong></span><span>股息率 <strong>${number(row.dividend_yield)}%</strong></span>`;return`<b>${title}</b><span>股债收益差 <strong>${number(row.bond_minus_dividend)}%</strong></span><span>Z-score <strong>${number(row.zscore)}</strong></span><span>信号 <strong>${row.signal_state||'历史不足'}</strong></span><span>建议仓位 <strong>${finite(row.proposed_allocation)?`${number(Number(row.proposed_allocation)*100,0)}%`:'—'}</strong></span>`}
function bindInteractions(target,key){if(target.dataset.interactiveBound)return;target.dataset.interactiveBound='true';let dragging=null;target.addEventListener('wheel',event=>{const ctx=target._chartContext;if(!ctx?.fullRows.length)return;event.preventDefault();const v=state.viewport[key],length=state.series.length,span=v.end-v.start,rect=target.getBoundingClientRect(),ratio=Math.min(1,Math.max(0,(event.clientX-rect.left)/rect.width)),next=Math.round(Math.min(length,Math.max(18,span*(event.deltaY<0?.78:1.28))),anchor=v.start+span*ratio);v.start=Math.max(0,Math.min(length-next,Math.round(anchor-next*ratio)));v.end=v.start+next;renderCharts()},{passive:false});target.addEventListener('pointerdown',event=>{const v=state.viewport[key];dragging={x:event.clientX,start:v.start,end:v.end};target.setPointerCapture(event.pointerId)});target.addEventListener('pointermove',event=>{const ctx=target._chartContext;if(!ctx)return;if(dragging){const v=state.viewport[key],span=dragging.end-dragging.start,rect=target.getBoundingClientRect(),shift=Math.round((dragging.x-event.clientX)/rect.width*span);v.start=Math.max(0,Math.min(state.series.length-span,dragging.start+shift));v.end=v.start+span;renderCharts();return}showTooltip(target,event)});target.addEventListener('pointerup',()=>dragging=null);target.addEventListener('pointerleave',()=>{dragging=null;const t=target.querySelector('.chart-tooltip'),g=target.querySelector('.crosshair');if(t)t.hidden=true;if(g)g.style.display='none'})}
function showTooltip(target,event){const c=target._chartContext;if(!c?.rows.length)return;const{width,pad,sx,sy,lines,grain}=c,rect=target.getBoundingClientRect(),relativeX=Math.max(pad.l,Math.min(width-pad.r,(event.clientX-rect.left)/rect.width*width)),index=Math.round((relativeX-pad.l)/(width-pad.l-pad.r)*Math.max(c.rows.length-1,1)),row=c.rows[Math.max(0,Math.min(c.rows.length-1,index))],value=lines[0].accessor(row),tip=target.querySelector('.chart-tooltip'),guide=target.querySelector('.crosshair'),x=sx(index),y=finite(value)?sy(Number(value)):0;tip.hidden=false;tip.innerHTML=tooltipHtml(c.key,row,grain);tip.style.left=`${Math.min(relativeX+16,width-210)}px`;tip.style.top='18px';guide.style.display='block';guide.querySelector('line').setAttribute('x1',x);guide.querySelector('line').setAttribute('x2',x);guide.querySelector('circle').setAttribute('cx',x);guide.querySelector('circle').setAttribute('cy',y);guide.querySelector('circle').style.display=finite(value)?'block':'none'}
function lineChart(target,key,empty){const fullRows=rangeData(key),grain=resolvedGrain(key,fullRows),rows=aggregate(fullRows,grain),lines=chartLines(key),values=rows.flatMap(r=>lines.map(l=>Number(l.accessor(r))).filter(Number.isFinite));if(!values.length){target.innerHTML=`<div class="chart-empty">${empty}</div>`;return}const width=Math.max(target.clientWidth||800,340),height=380,pad={l:56,r:18,t:16,b:40};let min=Math.min(...values),max=Math.max(...values);const span=Math.max(max-min,Math.abs(max)*.12,.1);min-=span*.12;max+=span*.12;const sx=i=>pad.l+i*(width-pad.l-pad.r)/Math.max(rows.length-1,1),sy=v=>pad.t+(max-v)*(height-pad.t-pad.b)/(max-min);let svg=`<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="可缩放历史数据图表">`;for(let i=0;i<5;i++){const value=min+(max-min)*i/4,y=sy(value);svg+=`<line class="grid-line" x1="${pad.l}" x2="${width-pad.r}" y1="${y}" y2="${y}"/><text class="axis-text" x="0" y="${y+4}">${number(value)}</text>`}[0,Math.floor((rows.length-1)/2),rows.length-1].forEach(i=>svg+=`<text class="axis-text" x="${sx(i)}" y="${height-10}" text-anchor="middle">${compactDate(rows[i].trade_date)}</text>`);lines.forEach(l=>svg+=`<path class="${l.className}" d="${pathFor(rows,l.accessor,sx,sy)}"/>`);svg+=`<g class="crosshair" style="display:none"><line y1="${pad.t}" y2="${height-pad.b}"/><circle r="4"/></g></svg><div class="chart-tooltip" hidden></div>`;target.innerHTML=svg;target._chartContext={key,fullRows,rows,grain,width,pad,sx,sy,lines};bindInteractions(target,key)}
function renderMetrics(summary){const last=summary.latest||{},cards=[['最新收盘',number(last.close),last.trade_date||'暂无数据'],['PE · TTM',number(last.pe_ttm_index),'iFinD 指数口径'],['PB · MRQ',number(last.pb_mrq),'iFinD 指数口径'],['股息率',finite(last.dividend_yield)?`${number(last.dividend_yield)}%`:'—','过去 12 月口径'],['股债 Z-score',number(last.zscore),last.signal_state||'历史样本不足']];document.querySelector('#metric-grid').innerHTML=cards.map(c=>`<article class="metric"><label>${c[0]}</label><strong>${c[1]}</strong><small>${c[2]}</small></article>`).join('')}
function renderSignal(summary){const base=Number(document.querySelector('#base-amount').value)||0,amount=Math.round(base*summary.suggested_factor),last=summary.latest||{};document.querySelector('#signal-rail').innerHTML=`<div><div class="label">本期手动定投参考</div><div class="state">${last.signal_state||'等待 Z-score 历史'}</div></div><div><div class="label">建议金额</div><div class="amount">¥ ${amount.toLocaleString()} <b>×${number(summary.suggested_factor)}</b></div></div><div class="mini">趋势门控<strong>${summary.trend||'数据不足'} · ×${number(summary.trend_factor)}</strong></div><div class="mini">估值弹性<strong>Z ${number(last.zscore)} · ×${number(summary.valuation_factor)}</strong></div><div class="mini">执行节奏<strong>月度复核 / 手动调整</strong></div>`;document.querySelector('#footer-note').textContent=summary.disclaimer||'';document.querySelector('#last-updated').textContent=last.trade_date?`DATA AS OF ${last.trade_date}`:'等待同步'}
function renderCharts(){lineChart(document.querySelector('#valuation-chart'),'valuation',`暂无 ${labels[state.metric]} 历史值；下次同步将补充。`);lineChart(document.querySelector('#spread-chart'),'spread','需要同日的历史股息率与 10 年国债收益率，且至少积累 756 个交易日才能显示标准差通道。');document.querySelectorAll('[data-chart-window]').forEach(el=>{const key=el.dataset.chartWindow,grain=resolvedGrain(key,rangeData(key)),count=state.viewport[key].end-state.viewport[key].start;el.textContent=`${grain==='day'?'日频':grain==='week'?'周频':'月频'} · ${count} 个交易日`})}
async function loadDashboard(){const[seriesPayload,summary]=await Promise.all([getJson(`/api/series?index_code=${encodeURIComponent(state.code)}`),getJson(`/api/summary?index_code=${encodeURIComponent(state.code)}`)]);state.series=seriesPayload.series||[];resetViewports();state.summary=summary;renderMetrics(summary);renderSignal(summary);renderCharts()}
function bindGrains(){document.querySelectorAll('[data-grain]').forEach(button=>button.addEventListener('click',()=>{const key=button.dataset.chart;state.viewport[key].grain=button.dataset.grain;document.querySelectorAll(`[data-chart="${key}"][data-grain]`).forEach(item=>item.classList.toggle('active',item===button));renderCharts()}))}
function bindTimeRanges(){document.querySelectorAll('[data-range-chart]').forEach(control=>control.addEventListener('change',()=>{applyRange(control.dataset.rangeChart,control.value);renderCharts()}))}
async function init(){try{const payload=await getJson('/api/indexes'),select=document.querySelector('#index-select');select.innerHTML=(payload.indexes||[]).map(i=>`<option value="${i.index_code}">${indexLabel(i.index_code)}</option>`).join('');if(!payload.indexes?.length)throw new Error(payload.message||'没有可展示的数据');if(payload.indexes.some(i=>i.index_code===state.code))select.value=state.code;else state.code=select.value;select.addEventListener('change',async e=>{state.code=e.target.value;await loadDashboard()});document.querySelector('#base-amount').addEventListener('input',()=>state.summary&&renderSignal(state.summary));document.querySelector('#metric-tabs').addEventListener('click',e=>{const b=e.target.closest('button[data-metric]');if(!b)return;state.metric=b.dataset.metric;document.querySelectorAll('#metric-tabs button').forEach(i=>i.classList.toggle('active',i===b));renderCharts()});bindGrains();await loadDashboard()}catch(error){document.querySelector('.hero').insertAdjacentHTML('afterend',`<div class="chart-empty">看板暂不可用：${error.message}</div>`)}}
window.addEventListener('resize',()=>state.series.length&&renderCharts());bindTimeRanges();init();
